-- 其余 4 个质控模块历史记录表。
-- 说明：
-- 1. 与 hemorrhage_records 保持同一建模方式：用户维度 + 患者检查信息 + 结果摘要 + 原始结果 JSON。
-- 2. 当前前端仍为 mock，但库表已提前补齐，后续接真实接口时可直接落库。
-- 3. 每张表都保留 qc_items_json / raw_result_json，兼容当前页面中的详细质控项结构。

CREATE TABLE IF NOT EXISTS `head_qc_records` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `patient_name` varchar(100) DEFAULT NULL,
  `exam_id` varchar(100) DEFAULT NULL,
  `accession_number` varchar(100) DEFAULT NULL,
  `gender` varchar(20) DEFAULT NULL,
  `age` int DEFAULT NULL,
  `study_date` date DEFAULT NULL,
  `device` varchar(100) DEFAULT NULL,
  `image_path` varchar(500) DEFAULT NULL,
  `slice_count` int DEFAULT NULL,
  `slice_thickness` decimal(6,2) DEFAULT NULL,
  `quality_score` decimal(5,1) DEFAULT NULL COMMENT '质控评分',
  `qc_status` varchar(20) NOT NULL DEFAULT '合格' COMMENT '质控结论：合格/不合格',
  `abnormal_count` int NOT NULL DEFAULT 0 COMMENT '异常项数量',
  `primary_issue` varchar(100) DEFAULT NULL COMMENT '主异常项',
  `analysis_duration` float DEFAULT NULL COMMENT '分析耗时(ms/秒，按服务实现口径存储)',
  `qc_items_json` longtext DEFAULT NULL COMMENT '质控项明细 JSON',
  `raw_result_json` longtext DEFAULT NULL COMMENT '原始响应 JSON',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_head_qc_user_created_at` (`user_id`, `created_at`),
  KEY `idx_head_qc_user_status_created` (`user_id`, `qc_status`, `created_at`),
  CONSTRAINT `head_qc_records_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `chest_non_contrast_qc_records` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `patient_name` varchar(100) DEFAULT NULL,
  `exam_id` varchar(100) DEFAULT NULL,
  `accession_number` varchar(100) DEFAULT NULL,
  `gender` varchar(20) DEFAULT NULL,
  `age` int DEFAULT NULL,
  `study_date` date DEFAULT NULL,
  `device` varchar(100) DEFAULT NULL,
  `image_path` varchar(500) DEFAULT NULL,
  `slice_count` int DEFAULT NULL,
  `slice_thickness` decimal(6,2) DEFAULT NULL,
  `quality_score` decimal(5,1) DEFAULT NULL COMMENT '质控评分',
  `qc_status` varchar(20) NOT NULL DEFAULT '合格' COMMENT '质控结论：合格/不合格',
  `abnormal_count` int NOT NULL DEFAULT 0 COMMENT '异常项数量',
  `primary_issue` varchar(100) DEFAULT NULL COMMENT '主异常项',
  `analysis_duration` float DEFAULT NULL COMMENT '分析耗时(ms/秒，按服务实现口径存储)',
  `qc_items_json` longtext DEFAULT NULL COMMENT '质控项明细 JSON',
  `raw_result_json` longtext DEFAULT NULL COMMENT '原始响应 JSON',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_chest_non_contrast_user_created_at` (`user_id`, `created_at`),
  KEY `idx_chest_non_contrast_user_status_created` (`user_id`, `qc_status`, `created_at`),
  CONSTRAINT `chest_non_contrast_qc_records_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `chest_contrast_qc_records` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `patient_name` varchar(100) DEFAULT NULL,
  `exam_id` varchar(100) DEFAULT NULL,
  `accession_number` varchar(100) DEFAULT NULL,
  `gender` varchar(20) DEFAULT NULL,
  `age` int DEFAULT NULL,
  `study_date` date DEFAULT NULL,
  `device` varchar(100) DEFAULT NULL,
  `image_path` varchar(500) DEFAULT NULL,
  `slice_count` int DEFAULT NULL,
  `slice_thickness` decimal(6,2) DEFAULT NULL,
  `flow_rate` decimal(6,2) DEFAULT NULL COMMENT '造影剂流速 mL/s',
  `contrast_volume` decimal(8,2) DEFAULT NULL COMMENT '造影剂总量 mL',
  `injection_site` varchar(100) DEFAULT NULL COMMENT '注射部位',
  `quality_score` decimal(5,1) DEFAULT NULL COMMENT '质控评分',
  `qc_status` varchar(20) NOT NULL DEFAULT '合格' COMMENT '质控结论：合格/不合格',
  `abnormal_count` int NOT NULL DEFAULT 0 COMMENT '异常项数量',
  `primary_issue` varchar(100) DEFAULT NULL COMMENT '主异常项',
  `analysis_duration` float DEFAULT NULL COMMENT '分析耗时(ms/秒，按服务实现口径存储)',
  `qc_items_json` longtext DEFAULT NULL COMMENT '质控项明细 JSON',
  `raw_result_json` longtext DEFAULT NULL COMMENT '原始响应 JSON',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_chest_contrast_user_created_at` (`user_id`, `created_at`),
  KEY `idx_chest_contrast_user_status_created` (`user_id`, `qc_status`, `created_at`),
  CONSTRAINT `chest_contrast_qc_records_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `coronary_cta_qc_records` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `patient_name` varchar(100) DEFAULT NULL,
  `exam_id` varchar(100) DEFAULT NULL,
  `accession_number` varchar(100) DEFAULT NULL,
  `gender` varchar(20) DEFAULT NULL,
  `age` int DEFAULT NULL,
  `study_date` date DEFAULT NULL,
  `device` varchar(100) DEFAULT NULL,
  `image_path` varchar(500) DEFAULT NULL,
  `slice_count` int DEFAULT NULL,
  `slice_thickness` decimal(6,2) DEFAULT NULL,
  `heart_rate` int DEFAULT NULL COMMENT '平均心率 bpm',
  `hr_variability` int DEFAULT NULL COMMENT '心率波动 bpm',
  `recon_phase` varchar(100) DEFAULT NULL COMMENT '重建相位',
  `kvp` varchar(50) DEFAULT NULL COMMENT '管电压',
  `quality_score` decimal(5,1) DEFAULT NULL COMMENT '质控评分',
  `qc_status` varchar(20) NOT NULL DEFAULT '合格' COMMENT '质控结论：合格/不合格',
  `abnormal_count` int NOT NULL DEFAULT 0 COMMENT '异常项数量',
  `primary_issue` varchar(100) DEFAULT NULL COMMENT '主异常项',
  `analysis_duration` float DEFAULT NULL COMMENT '分析耗时(ms/秒，按服务实现口径存储)',
  `qc_items_json` longtext DEFAULT NULL COMMENT '质控项明细 JSON',
  `raw_result_json` longtext DEFAULT NULL COMMENT '原始响应 JSON',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_coronary_cta_user_created_at` (`user_id`, `created_at`),
  KEY `idx_coronary_cta_user_status_created` (`user_id`, `qc_status`, `created_at`),
  CONSTRAINT `coronary_cta_qc_records_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;